services:
  postgres:
    image: postgres
    container_name: bill-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bill-service-db

    ports:
      - "5432:5432"
    networks:
      -postgres:
    restart: unless-stopped

  app:
    build: .
    container_name: bill-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bill-service-db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
